using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("2015.12.10.1446")]
[assembly: AssemblyFileVersionAttribute("2015.12.10.1446")]
[assembly: AssemblyCopyrightAttribute("Copyright 2015")]
[assembly: AssemblyProductAttribute("Rodney-TeamCityTestApplication")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("2015.12.10.1446")]
